In [2]:
# import modules
from matplotlib import pyplot as plt
import matplotlib.cm as cm
import numpy.ma as ma
import numpy as np
import netCDF4 as nc4
import wx
import xarray as xr
%matplotlib inline

#pypago
import sys
sys.path.insert(0,"/home/albert/lib/python/pypago")
import pypago

from netCDF4 import Dataset
import sys, os
import wx
import pypago
from matplotlib.figure import Figure
from matplotlib.backends.backend_wxagg import FigureCanvasWxAgg as FigureCanvas
from matplotlib.backends.backend_wxagg import NavigationToolbar2Wx
import matplotlib
import pylab as plt
import numpy as np
from mpl_toolkits.basemap import Basemap
from matplotlib import rcParams
rcParams['lines.linewidth'] = 2

from __param__ import *


In [15]:
gridname='/media/extra/DATA/NACHOS12.L75/NACHOS12.L75-I/NACHOS12.L75-MAA13_mesh_mask.nc'

lont=np.squeeze(pypago.readnc(gridname,'nav_lon'));
latt=np.squeeze(pypago.readnc(gridname,'nav_lat'));
zt=np.squeeze(pypago.readnc(gridname,'gdept_1d'));
bathy_temp=np.squeeze(pypago.readnc(gridname,'mbathy')).astype(np.int);
bathy_temp[bathy_temp<0]=0;
bathy=zt[bathy_temp]
mask_temp=np.squeeze(pypago.readnc(gridname,'tmask'));
mask=np.squeeze(mask_temp[0,:,:]);
[nj,ni]=mask.shape



In [5]:
sections = [] # initialisation of the section list (default: empty list)
numbernew = 1
lonint=np.array((-56,-48)).astype(np.float) # we recover the variables of lon,lat
latint=np.array((53.5,60.5)).astype(np.float)


In [6]:
lont.shape

(1568, 1609)

In [7]:
latt.shape

(1568, 1609)

In [8]:
lonint

array([-56., -48.])

In [10]:
latint

array([ 53.5,  60.5])

In [11]:
[nj,ni]=lont.shape

In [18]:
c=np.max(np.abs(latt[1:,:]-latt[0:-1,:]))
print c


0.0833333


In [19]:
a=np.max(np.abs(lont[1:,:]-lont[0:-1,:]))
b=np.max(np.abs(lont[:,1:]-lont[:,0:-1]))
step_x=np.max([a,b]);

c=np.max(np.abs(latt[1:,:]-latt[0:-1,:]))
d=np.max(np.abs(latt[:,1:]-latt[:,0:-1]))
step_y=np.max([c,d]);

vecj=np.empty(len(lonint))
veci=np.empty(len(lonint))


In [20]:
off=1
[j,i]=np.nonzero((lont<=lonint[0]+off*step_x)&(lont>=lonint[0]-off*step_x)&(latt<=latint[0]+off*step_y)&(latt>=latint[0]-off*step_y))

In [21]:
j

array([1003, 1003, 1003, 1003, 1003, 1003, 1004, 1004, 1004, 1004, 1004,
       1005, 1005, 1005, 1005, 1005, 1006, 1006])

In [22]:
i

array([518, 519, 520, 521, 522, 523, 519, 520, 521, 522, 523, 519, 520,
       521, 522, 523, 519, 520])

In [25]:
len(j)

18

In [28]:
def distance(lat1,lon1,lat2,lon2,geoid):
    az12,az21,dist = geoid.inv(lon1,lat1,lon2,lat2)
    return dist

dis=np.empty(len(j))
for ii in range(0,len(j)):
    dis[ii]=np.abs(distance(latint[0],lonint[0],latt[j[ii],i[ii]],lont[j[ii],i[ii]],ee))
ind=np.argmin(dis)

In [29]:
ind

8

In [30]:
vecj[0]=j[ind]
veci[0]=i[ind]

In [32]:
vecj

array([  1.00400000e+003,   4.94065646e-324])

In [37]:
latt[518,1003]

22.944302

In [38]:
lonint

array([-56., -48.])

In [39]:
step_x

0.24533081

In [40]:
lonint[0]+off*step_x

-55.754669189453125

In [41]:
lonint[0]-off*step_x

-56.245330810546875

In [42]:
latint[0]+off*step_y

53.583333306014538

In [43]:
latint[0]-off*step_y

53.416666693985462